In [1]:
import pandas as pd
import numpy as np

In [2]:
#TODO Replace with proper query invocation on a server 
def get_data():
    data = pd.read_csv("data/query-result.csv")
    return data
data = get_data()
data.head()

,pnode,person,a1,kr,anode,snode,authority,a2,knode,kinsman,a3,kt,kinship
0,https://r11.eu/rdf/resource/6f21cc33-baa9-417f...,"Aaron, brother of Alousianos",https://r11.eu/rdf/resource/c2557e72-877c-4d95...,https://r11.eu/rdf/resource/040129a5-d270-47a4...,https://r11.eu/rdf/resource/37ade4c7-baf2-4bec...,https://r11.eu/rdf/resource/2ca67aa0-2865-489a...,"Ioannes Skylitzes, historian",https://r11.eu/rdf/resource/395e8c9f-ee41-47ff...,https://r11.eu/rdf/resource/0f7afd6a-cdd8-4a6e...,"Alousianos, son of Ioannes/John Vladislav",https://r11.eu/rdf/resource/9f4cb43e-0574-4238...,https://r11.eu/rdf/resource/327507a9-575b-4770...,father (brother)
1,https://r11.eu/rdf/resource/6f21cc33-baa9-417f...,"Aaron, brother of Alousianos",https://r11.eu/rdf/resource/c2557e72-877c-4d95...,https://r11.eu/rdf/resource/040129a5-d270-47a4...,https://r11.eu/rdf/resource/37ade4c7-baf2-4bec...,https://r11.eu/rdf/resource/2ca67aa0-2865-489a...,"Ioannes Skylitzes, historian",https://r11.eu/rdf/resource/d0249602-4e27-4f29...,https://r11.eu/rdf/resource/0f7afd6a-cdd8-4a6e...,"Alousianos, son of Ioannes/John Vladislav",https://r11.eu/rdf/resource/9f4cb43e-0574-4238...,https://r11.eu/rdf/resource/327507a9-575b-4770...,father (brother)
2,https://r11.eu/rdf/resource/6f21cc33-baa9-417f...,"Aaron, brother of Alousianos",https://r11.eu/rdf/resource/1e72cf30-435d-4e18...,https://r11.eu/rdf/resource/040129a5-d270-47a4...,https://r11.eu/rdf/resource/7231f2c2-e72b-4cd6...,https://r11.eu/rdf/resource/5e0cf666-5cc7-4b8d...,Ioannes Zonaras,https://r11.eu/rdf/resource/395e8c9f-ee41-47ff...,https://r11.eu/rdf/resource/0f7afd6a-cdd8-4a6e...,"Alousianos, son of Ioannes/John Vladislav",https://r11.eu/rdf/resource/9f4cb43e-0574-4238...,https://r11.eu/rdf/resource/327507a9-575b-4770...,father (brother)
3,https://r11.eu/rdf/resource/6f21cc33-baa9-417f...,"Aaron, brother of Alousianos",https://r11.eu/rdf/resource/1e72cf30-435d-4e18...,https://r11.eu/rdf/resource/040129a5-d270-47a4...,https://r11.eu/rdf/resource/7231f2c2-e72b-4cd6...,https://r11.eu/rdf/resource/5e0cf666-5cc7-4b8d...,Ioannes Zonaras,https://r11.eu/rdf/resource/d0249602-4e27-4f29...,https://r11.eu/rdf/resource/0f7afd6a-cdd8-4a6e...,"Alousianos, son of Ioannes/John Vladislav",https://r11.eu/rdf/resource/9f4cb43e-0574-4238...,https://r11.eu/rdf/resource/327507a9-575b-4770...,father (brother)
4,https://r11.eu/rdf/resource/6f21cc33-baa9-417f...,"Aaron, brother of Alousianos",https://r11.eu/rdf/resource/c2557e72-877c-4d95...,https://r11.eu/rdf/resource/040129a5-d270-47a4...,https://r11.eu/rdf/resource/37ade4c7-baf2-4bec...,https://r11.eu/rdf/resource/2ca67aa0-2865-489a...,"Ioannes Skylitzes, historian",https://r11.eu/rdf/resource/395e8c9f-ee41-47ff...,https://r11.eu/rdf/resource/0f7afd6a-cdd8-4a6e...,"Alousianos, son of Ioannes/John Vladislav",https://r11.eu/rdf/resource/30834ba5-213c-4931...,https://r11.eu/rdf/resource/327507a9-575b-4770...,father (brother)

In [16]:
x = 'Emperor Romanos III Argyros'
y = 'Basileios Skleros, son of Romanos Skleros'

data[(data['kinsman'] == 'Emperor Romanos III Argyros') & (data['a1'] > 'Basileios Skleros, son of Romanos Skleros') & data['kinship']=='brother-in-law']

Empty DataFrame
Columns: [pnode, person, a1, kr, anode, snode, authority, a2, knode, kinsman, a3, kt, kinship]
Index: []

In [4]:
# Load Ontology definision file 
#https://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.html
from rdflib import Graph, Namespace, RDF, RDFS, OWL
g = Graph()
g.parse("https://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.owl",format='xml')

def extract_object_properties(graph):
    object_properties = []
    for s, p, o in graph.triples((None, RDF.type, OWL.ObjectProperty)):
        for label in graph.objects(s, RDFS.label):
            if label.language == 'en':
                object_properties.append((s, label))
                break  # If we found an English label, no need to check further
    return object_properties

# Extract and print object properties
object_properties = extract_object_properties(g)
print("Object Properties in the Ontology:")
for prop, label in object_properties:
    print(f"{label} ({prop})")

Object Properties in the Ontology:
AncestorOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1)
GreatGrandParentOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.1)
GreatGrandMotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.1.1)
GreatGrandFatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.1.2)
GrandParentOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.2)
GrandMotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.2.1)
GrandFatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.2.2)
ParentOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3)
MotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.1)
LegalMotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.1.1)
BiologicalMotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.1.2)
EggDonorOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.1.3)
NaturalMotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.1.4)
SurrogateOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.1.5)
FatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.2)
LegalFatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.2.1)
BiologicalFatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.2.2)
DonorFatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.2.3)
NaturalFatherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#1.3.2.4)
NieceOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#10)
NephewOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#11)
SeparatedFrom (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12)
ExCommonLawWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.1.1)
ExWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.1.2)
ExGayWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.1.2.1)
ExStraightWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.1.2.2)
ExPolyandrousWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.1.2.3)
WidowOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.1.3)
ExCommonLawHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.2.1)
ExHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.2.2)
ExGayHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.2.2.1)
ExStraightHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.2.2.2)
ExPolygynousHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.2.2.3)
WidowerOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#12.2.3)
PartnerOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13)
CommonLawWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.1.1)
WifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.1.2)
GayWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.1.2.1)
StraightWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.1.2.2)
PolyandrousWifeOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.1.2.3)
CommonLawHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.2.1)
HusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.2.2)
GayHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.2.2.1)
StraightHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.2.2.2)
PolygynousHusbandOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#13.2.2.3)
CousinOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#2)
DescendantOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3)
ChildOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1)
DaughterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.1)
AdoptedDaughterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.1.1)
BiologicalDaughterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.1.2)
GivenGirlOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.1.3)
NaturalDaughterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.1.4)
SurrogateDaughterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.1.5)
SonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.2)
AdoptedSonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.2.1)
BiologicalSonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.2.2)
GivenSonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.2.3)
NaturalSonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.2.4)
SurrogateSonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.1.2.5)
GrandChildOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.2)
GrandDaughterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.2.1)
GrandSonOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#3.2.2)
HalfSiblingOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#4)
HalfSisterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#4.1)
HalfBrotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#4.2)
SiblingOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#5)
SisterOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#5.1)
BrotherOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#5.2)
DaughterInLawOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#6)
SonInLawOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#7)
AuntOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#8)
UncleOf (http://cedric.cnam.fr/~hamdif/ontologies/PersonLink.owl#9)

In [5]:
#TODO full maping one into another 
# few most common 
# RELEVEN DATA
releven_relations = [
    ['husband','husband (betrothed)', 'husband (by illicit marriage)'],
    ['half-sister'],
    ["half-brother"],
    # ["great-grandson"],
    # ["great uncle"],
    ["daughter"]
    ]

kinship_relations = [
    ["HusbandOf"],
    ["HalfSisterOf"],
    ["HalfBrotherOf"],
    ["DaughterOf"] #TODO
]

In [16]:
from owlready2 import *
import re

# Load the ontology
ontology_path = "https://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.owl"
onto = get_ontology(ontology_path).load()

# Regular expression to extract variables
variable_pattern = re.compile(r'\?(\w+)')

# Function to extract variables from a rule atom
def extract_variables(atom):
    return set(variable_pattern.findall(str(atom)))

# Function to check rules
def check_rules(onto):
    for rule in onto.rules():
        body_vars = set()
        head_vars = set()
        
        for atom in rule.body:
            body_vars.update(extract_variables(atom))
        
        for atom in rule.head:
            head_vars.update(extract_variables(atom))
        
        # Check if all head variables are in body variables
        if not head_vars.issubset(body_vars):
            print(f"Problematic Rule: {rule}")
            print(f"Head variables {head_vars - body_vars} not found in body variables.")

# Run the check
check_rules(onto)

Problematic Rule: 1.3.2(?x, ?y), 1.3.2(?y, ?z) -> 1.2.2(?x, ?a)
Head variables {'a'} not found in body variables.
Problematic Rule: 1.3.1(?y, ?z), 1.3.2(?x, ?y) -> 1.2.2(?x, ?a)
Head variables {'a'} not found in body variables.
Problematic Rule: Femme(?x), 3.1.1(?x, ?y), 5.1(?y, ?z) -> 10.1(?x, ?a)
Head variables {'a'} not found in body variables.

## Interpretation of a rule 
FatherOf(?x, ?y), FatherOf(?y, ?z) -> GrandFatherOf(?x, ?a)
### Condition
 - FatherOf(?x, ?y): This indicates that ?x is the father of ?y.
 - FatherOf(?y, ?z): This indicates that ?y is the father of ?z.

### Conclusion
 - GrandFatherOf(?x, ?a): This is the conclusion we want to draw, stating that ?x is the grandfather of ?a.

In [2]:
from owlready2 import *
import re

# Correction 

ontology_path = "https://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.owl"
onto = get_ontology(ontology_path).load(reload=True)

# Regular expression to extract variables
variable_pattern = re.compile(r'\?(\w+)')

# Function to extract variables from a rule atom
def extract_variables(atom):
    return set(variable_pattern.findall(str(atom)))

# Function to identify and print problematic rules
def check_rules(onto):
    problematic_rules = []
    for rule in onto.rules():
        body_vars = set()
        head_vars = set()
        
        for atom in rule.body:
            body_vars.update(extract_variables(atom))
        
        for atom in rule.head:
            head_vars.update(extract_variables(atom))
        
        # Check if all head variables are in body variables
        if not head_vars.issubset(body_vars):
            print(f"Problematic Rule: {rule}")
            print(f"Head variables {head_vars - body_vars} not found in body variables.")
            problematic_rules.append(rule)
    return problematic_rules

# Identify problematic rules
print("=======PROBLEMATIC RULES=======")
problematic_rules = check_rules(onto)

def remove_problematic_rules(onto, rules):
    with onto:
        for rule in rules:
            destroy_entity(rule)
            print(f"Removed Problematic Rule: {rule}")

print("=======REMOVED RULES=======")
remove_problematic_rules(onto, problematic_rules)


# def add_corrected_rules(onto):
#     with onto:
#         # Add corrected rules
#         new_rule1 = Imp()
#         new_rule1.set_as_rule([onto.FatherOf("?x", "?y"), onto.FatherOf("?y", "?z")], [onto.GrandFatherOf("?x", "?z")])

#         new_rule2 = Imp()
#         new_rule2.set_as_rule([onto.MotherOf("?y", "?z"), onto.FatherOf("?x", "?y")], [onto.GrandFatherOf("?x", "?z")])

#         new_rule3 = Imp()
#         new_rule3.set_as_rule([onto.Female("?x"), onto.DaughterOf("?x", "?y"), onto.SisterOf("?y", "?z")], [onto["ابنة الاخت ل"]("?x", "?z")])


# add_corrected_rules(onto)
print("=======CHECK IF ONTOLOGY CLEAN=======")
check_rules(onto)
onto.save(file="data/corrected_ontology.owl")

=======PROBLEMATIC RULES=======
Problematic Rule: 1.3.2(?x, ?y), 1.3.2(?y, ?z) -> 1.2.2(?x, ?a)
Head variables {'a'} not found in body variables.
Problematic Rule: 1.3.1(?y, ?z), 1.3.2(?x, ?y) -> 1.2.2(?x, ?a)
Head variables {'a'} not found in body variables.
Problematic Rule: Femme(?x), 3.1.1(?x, ?y), 5.1(?y, ?z) -> 10.1(?x, ?a)
Head variables {'a'} not found in body variables.
=======REMOVED RULES=======
Removed Problematic Rule: 1.3.2(?x, ?y), 1.3.2(?y, ?z) -> 1.2.2(?x, ?a)
Removed Problematic Rule: 1.3.1(?y, ?z), 1.3.2(?x, ?y) -> 1.2.2(?x, ?a)
Removed Problematic Rule: Femme(?x), 3.1.1(?x, ?y), 5.1(?y, ?z) -> 10.1(?x, ?a)
=======CHECK IF ONTOLOGY CLEAN=======

In [1]:
from owlready2 import *
import re

# Load the ontology
ontology_path = "data\corrected_ontology.owl"
onto = get_ontology(ontology_path).load(reload=True)

# Regular expression to extract variables
variable_pattern = re.compile(r'\?(\w+)')

# Function to extract variables from a rule atom
def extract_variables(atom):
    return set(variable_pattern.findall(str(atom)))

# Function to get the label of an entity in English
def get_label(entity):
    if entity.label:
        for label in entity.label:
            if label.lang == "en":
                return label
        return entity.label.first()
    else:
        return entity.name

# Function to convert a rule atom to a labeled string
def convert_atom_to_label(atom):
    parts = atom.split("(")
    predicate = parts[0]
    variables = parts[1][:-1]  # remove the trailing ')'
    predicate_label = get_label(onto[predicate])
    return f"{predicate_label}({variables})"

# Function to convert a rule to a labeled string
def convert_rule_to_labels(rule):
    body = ", ".join([convert_atom_to_label(str(atom)) for atom in rule.body])
    head = ", ".join([convert_atom_to_label(str(atom)) for atom in rule.head])
    return f"{body} -> {head}"

# Function to print all rules in the ontology with English labels
def print_all_rules_with_labels(onto):
    for rule in onto.rules():
        labeled_rule = convert_rule_to_labels(rule)
        print(f"Rule: {labeled_rule}")

# Print all rules with English names
print_all_rules_with_labels(onto)

<>:5: SyntaxWarning: invalid escape sequence '\c'
<>:5: SyntaxWarning: invalid escape sequence '\c'
C:\Users\ja.borowski\AppData\Local\Temp\ipykernel_39100\38471498.py:5: SyntaxWarning: invalid escape sequence '\c'
  ontology_path = "data\corrected_ontology.owl"

Rule: إبنة خالة ل(?x, ?y) -> CousineDe(?x, ?y)
Rule: Female(?z), MotherOf(?y, ?z), FatherOf(?x, ?y) -> GrandDaughterOf(?z, ?x)
Rule: SonOf(?x, ?y), UncleOf(?y, ?z) -> CousinDe(?x, ?z)
Rule: GrandMotherOf(?y, ?z), MotherOf(?x, ?y) -> GreatGrandMotherOf(?x, ?z)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), BrotherOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: GivenSonOf(?x, ?y) -> SonOf(?x, ?y)
Rule: Female(?y), MotherOf(?z, ?a), CommonLawHusbandOf(?x, ?y), SiblingOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: MotherOf(?z, ?a), DaughterOf(?x, ?y), HalfSisterOf(?y, ?z) -> إبنة خالة ل(?x, ?a)
Rule: Female(?x), CommonLawWifeOf(?x, ?y), خال ل(?y, ?z) -> زوجة الخال ل(?x, ?z)
Rule: FatherOf(?y, ?z), NieceOf(?x, ?y) -> CousineDe(?x, ?z)
Rule: MotherOf(?y, ?z), إبن الأ خت ل(?x, ?y) -> CousinOf(?x, ?z)
Rule: Female(?z), DaughterOf(?x, ?y), DaughterOf(?y, ?z) -> GrandMotherOf(?z, ?x)
Rule: Male(?a), DaughterOf(?y, ?z), DaughterOf(?z, ?a), SiblingOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: Male(?a), DaughterOf(?y, ?z), DaughterOf(?z, ?a), SisterOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: MotherOf(?z, ?a), CommonLawHusbandOf(?x, ?y), HalfSisterOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: MotherOf(?z, ?a), SonOf(?x, ?y), SiblingOf(?y, ?z) -> CousinDe(?x, ?a)
Rule: Male(?x), FatherOf(?z, ?a), PartnerOf(?x, ?y), SisterOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: Male(?a), SonOf(?y, ?z), SonOf(?z, ?a), SisterOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: Male(?x), CousinOf(?x, ?y) -> CousinDe(?x, ?y)
Rule: Female(?z), GrandSonOf(?y, ?z), SisterOf(?x, ?y) -> GrandMotherOf(?z, ?x)
Rule: DaughterOf(?x, ?y), عم ل(?y, ?z) -> CousinOf(?x, ?z)
Rule: Male(?a), SonOf(?x, ?y), SonOf(?y, ?z), SonOf(?z, ?a) -> GreatGrandFatherOf(?a, ?x)
Rule: Male(?a), DaughterOf(?z, ?a), SonOf(?y, ?z), SisterOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: MotherOf(?x, ?y), SisterOf(?y, ?z) -> MotherOf(?x, ?z)
Rule: BiologicalMotherOf(?x, ?y) -> MotherOf(?x, ?y)
Rule: DaughterOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: Female(?y), FatherOf(?z, ?a), CommonLawHusbandOf(?x, ?y), SiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: GrandSonOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: DaughterOf(?x, ?y), عمة ل(?y, ?z) -> CousinOf(?x, ?z)
Rule: Male(?x), مرتبط ب (?x, ?y), DaughterOf(?y, ?z) -> SonInLawOf(?x, ?z)
Rule: Female(?x), DaughterOf(?x, ?y), HalfSisterOf(?y, ?z) -> NieceOf(?x, ?z)
Rule: Male(?y), FatherOf(?z, ?a), StraightWifeOf(?x, ?y), HalfSiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: زوجة الخال ل(?x, ?y) -> AuntOf(?x, ?y)
Rule: Female(?a), DaughterOf(?y, ?z), SonOf(?z, ?a), SiblingOf(?x, ?y) -> GrandMotherOf(?a, ?x)
Rule: Female(?x), Male(?y), MotherOf(?z, ?a), مرتبطة ب(?x, ?y), HalfSiblingOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: إبنة خالة ل(?x, ?y) -> CousinOf(?x, ?y)
Rule: Male(?a), DaughterOf(?z, ?a), SonOf(?y, ?z), SiblingOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: FatherOf(?y, ?z), BrotherOf(?x, ?y) -> UncleOf(?x, ?z)
Rule: Female(?x), FatherOf(?y, ?z), SiblingOf(?x, ?y) -> AuntOf(?x, ?z)
Rule: MotherOf(?y, ?z), HalfBrotherOf(?x, ?y) -> UncleOf(?x, ?z)
Rule: Male(?x), SeparatedFrom(?x, ?y) -> SéparéDe(?x, ?y)
Rule: Female(?x), FatherOf(?z, ?a), PartnerOf(?x, ?y), BrotherOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: Female(?x), PacséeÀ(?x, ?y), SonOf(?y, ?z) -> DaughterInLawOf(?x, ?z)
Rule: Male(?x), MotherOf(?y, ?z), HalfSiblingOf(?x, ?y) -> خال ل(?x, ?z)
Rule: ابنة الاخت ل(?x, ?y) -> NieceOf(?x, ?y)
Rule: PacséÀ(?x, ?y), خالة ل(?y, ?z) -> زوج الخالة ل (?x, ?z)
Rule: Female(?z), MotherOf(?x, ?y), BrotherOf(?y, ?z) -> DaughterOf(?z, ?x)
Rule: GreatGrandMotherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: PolygynousHusbandOf(?x, ?y), خالة ل(?y, ?z) -> زوج الخالة ل (?x, ?z)
Rule: GayHusbandOf(?x, ?y) -> PartnerOf(?x, ?y)
Rule: Female(?x), DaughterOf(?x, ?y), DaughterOf(?y, ?z) -> GrandDaughterOf(?x, ?z)
Rule: MotherOf(?z, ?a), PacséÀ(?x, ?y), SisterOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: BiologicalSonOf(?x, ?y) -> SonOf(?x, ?y)
Rule: Female(?y), FatherOf(?z, ?a), مرتبط ب (?x, ?y), SiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: Male(?z), DaughterOf(?y, ?z), GrandDaughterOf(?x, ?y) -> GreatGrandFatherOf(?z, ?x)
Rule: Female(?a), DaughterOf(?x, ?y), DaughterOf(?y, ?z), DaughterOf(?z, ?a) -> GreatGrandMotherOf(?a, ?x)
Rule: MotherOf(?x, ?y), FatherOf(?y, ?z) -> GrandMotherOf(?x, ?z)
Rule: Female(?y), MotherOf(?z, ?a), PacséÀ(?x, ?y), HalfSiblingOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: GrandFatherOf(?x, ?y), GrandFatherOf(?x, ?z) -> CousinOf(?y, ?z)
Rule: Female(?z), DaughterOf(?x, ?y), SonOf(?y, ?z) -> GrandMotherOf(?z, ?x)
Rule: Female(?x), MotherOf(?z, ?a), PartnerOf(?x, ?y), HalfBrotherOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: NaturalDaughterOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: Male(?z), GrandSonOf(?y, ?z), SiblingOf(?x, ?y) -> GrandFatherOf(?z, ?x)
Rule: Male(?x), StraightHusbandOf(?x, ?y), DaughterOf(?y, ?z) -> SonInLawOf(?x, ?z)
Rule: MotherOf(?z, ?a), SonOf(?x, ?y), BrotherOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: Male(?y), FatherOf(?z, ?a), مرتبطة ب(?x, ?y), HalfSiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: FatherOf(?z, ?a), PolygynousHusbandOf(?x, ?y), SisterOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: PacséeÀ(?x, ?y) -> PartnerOf(?x, ?y)
Rule: FatherOf(?x, ?y), BrotherOf(?y, ?z) -> FatherOf(?x, ?z)
Rule: MotherOf(?y, ?z), NieceOf(?x, ?y) -> CousineDe(?x, ?z)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), SisterOf(?y, ?z) -> CousinDe(?x, ?a)
Rule: DaughterOf(?x, ?y), عمة ل(?y, ?z) -> إبنة عمة ل(?x, ?z)
Rule: Male(?y), FatherOf(?z, ?a), PolyandrousWifeOf(?x, ?y), SiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: GreatGrandFatherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), HalfSisterOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: DaughterOf(?x, ?y), UncleOf(?y, ?z) -> CousineDe(?x, ?z)
Rule: Female(?x), DaughterOf(?x, ?y), SiblingOf(?y, ?z) -> NieceOf(?x, ?z)
Rule: MotherOf(?y, ?z), ابنة الاخت ل(?x, ?y) -> CousineDe(?x, ?z)
Rule: Female(?y), MotherOf(?z, ?a), مرتبط ب (?x, ?y), SiblingOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: Male(?z), DaughterOf(?x, ?y), SonOf(?y, ?z) -> GrandFatherOf(?z, ?x)
Rule: CommonLawWifeOf(?x, ?y), عم ل(?y, ?z) -> زوجة العم ل(?x, ?z)
Rule: FatherOf(?y, ?z), ابنة الاخت ل(?x, ?y) -> CousineDe(?x, ?z)
Rule: Male(?y), FatherOf(?z, ?a), مرتبطة ب(?x, ?y), SiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: MotherOf(?x, ?y), MotherOf(?y, ?z) -> GrandMotherOf(?x, ?z)
Rule: Female(?y), FatherOf(?z, ?a), PolygynousHusbandOf(?x, ?y), SiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: Male(?x), FatherOf(?z, ?a), PartnerOf(?x, ?y), HalfSisterOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: MotherOf(?x, ?y), MotherOf(?y, ?z), MotherOf(?z, ?a) -> GreatGrandMotherOf(?x, ?a)
Rule: Male(?z), MotherOf(?x, ?y), FatherOf(?y, ?z) -> GrandSonOf(?z, ?x)
Rule: PolygynousHusbandOf(?x, ?y) -> PartnerOf(?x, ?y)
Rule: زوجة العم ل(?x, ?y) -> AuntOf(?x, ?y)
Rule: HalfSisterOf(?x, ?y) -> HalfSiblingOf(?x, ?y)
Rule: إبن خالة ل(?x, ?y) -> CousinOf(?x, ?y)
Rule: Male(?x), FatherOf(?y, ?z), HalfSiblingOf(?x, ?y) -> UncleOf(?x, ?z)
Rule: إبن الأخ ل(?x, ?y) -> NephewOf(?x, ?y)
Rule: CousinDe(?x, ?y) -> CousinOf(?x, ?y)
Rule: Male(?a), DaughterOf(?z, ?a), SonOf(?x, ?y), SonOf(?y, ?z) -> GreatGrandFatherOf(?a, ?x)
Rule: Female(?y), FatherOf(?z, ?a), مرتبط ب (?x, ?y), HalfSiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: DaughterOf(?x, ?y), AuntOf(?y, ?z) -> CousineDe(?x, ?z)
Rule: Male(?z), MotherOf(?x, ?y), BrotherOf(?y, ?z) -> SonOf(?z, ?x)
Rule: MotherOf(?z, ?a), PolyandrousWifeOf(?x, ?y), BrotherOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: Female(?x), PolyandrousWifeOf(?x, ?y), SonOf(?y, ?z) -> DaughterInLawOf(?x, ?z)
Rule: Male(?x), PolygynousHusbandOf(?x, ?y), DaughterOf(?y, ?z) -> SonInLawOf(?x, ?z)
Rule: PacséÀ(?x, ?y) -> مرتبط ب (?x, ?y)
Rule: MotherOf(?z, ?a), مرتبط ب (?x, ?y), HalfSisterOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: Female(?x), StraightWifeOf(?x, ?y), خال ل(?y, ?z) -> زوجة الخال ل(?x, ?z)
Rule: BiologicalMotherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: Female(?y), Male(?x), MotherOf(?z, ?a), PartnerOf(?x, ?y), SiblingOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: MotherOf(?z, ?a), SonOf(?x, ?y), HalfBrotherOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: NaturalFatherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: Female(?z), DaughterOf(?y, ?z), GrandDaughterOf(?x, ?y) -> GreatGrandMotherOf(?z, ?x)
Rule: Female(?a), DaughterOf(?y, ?z), DaughterOf(?z, ?a), SisterOf(?x, ?y) -> GrandMotherOf(?a, ?x)
Rule: FatherOf(?y, ?z), BrotherOf(?x, ?y) -> عم ل(?x, ?z)
Rule: MotherOf(?z, ?a), DaughterOf(?x, ?y), HalfSisterOf(?y, ?z) -> CousineDe(?x, ?a)
Rule: Male(?x), MotherOf(?b, ?a), MotherOf(?z, ?x), FatherOf(?y, ?a), FatherOf(?y, ?x) -> HalfBrotherOf(?x, ?a)
Rule: Female(?y), Male(?x), FatherOf(?z, ?a), PartnerOf(?x, ?y), SiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: ابنة عم ل(?x, ?y) -> CousineDe(?x, ?y)
Rule: Male(?x), MotherOf(?y, ?a), MotherOf(?y, ?x), FatherOf(?z, ?a), FatherOf(?z, ?x) -> SisterOf(?x, ?a)
Rule: Male(?y), MotherOf(?z, ?a), PacséeÀ(?x, ?y), HalfSiblingOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: ابنة عم ل(?x, ?y) -> CousinOf(?x, ?y)
Rule: FatherOf(?z, ?a), StraightWifeOf(?x, ?y), HalfBrotherOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: Female(?x), MotherOf(?y, ?z), SisterOf(?x, ?y) -> AuntOf(?x, ?z)
Rule: Female(?a), DaughterOf(?x, ?y), SonOf(?y, ?z), SonOf(?z, ?a) -> GreatGrandMotherOf(?a, ?x)
Rule: LegalFatherOf(?x, ?y) -> FatherOf(?x, ?y)
Rule: MotherOf(?z, ?a), DaughterOf(?x, ?y), HalfSiblingOf(?y, ?z) -> CousineDe(?x, ?a)
Rule: AdoptedSonOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: SurrogateSonOf(?x, ?y) -> SonOf(?x, ?y)
Rule: إبنة عمة ل(?x, ?y) -> CousinOf(?x, ?y)
Rule: MotherOf(?x, ?y), MotherOf(?z, ?a), FatherOf(?y, ?z) -> GreatGrandMotherOf(?x, ?a)
Rule: Female(?x), MotherOf(?y, ?a), MotherOf(?y, ?x), FatherOf(?b, ?a), FatherOf(?z, ?x) -> HalfSisterOf(?x, ?a)
Rule: FatherOf(?y, ?z), HalfBrotherOf(?x, ?y) -> عم ل(?x, ?z)
Rule: Male(?y), FatherOf(?z, ?a), PacséeÀ(?x, ?y), SiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: SurrogateDaughterOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: Female(?a), DaughterOf(?z, ?a), SonOf(?y, ?z), SiblingOf(?x, ?y) -> GrandMotherOf(?a, ?x)
Rule: Female(?x), مرتبطة ب(?x, ?y), خال ل(?y, ?z) -> زوجة الخال ل(?x, ?z)
Rule: MotherOf(?y, ?z), إبن الأخ ل(?x, ?y) -> ابن خال ل (?x, ?z)
Rule: SurrogateDaughterOf(?x, ?y) -> DaughterOf(?x, ?y)
Rule: LegalFatherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: Male(?z), GrandSonOf(?y, ?z), BrotherOf(?x, ?y) -> GrandFatherOf(?z, ?x)
Rule: WidowerOf(?x, ?y) -> SeparatedFrom(?x, ?y)
Rule: Male(?z), FatherOf(?x, ?y), BrotherOf(?y, ?z) -> SonOf(?z, ?x)
Rule: Female(?y), Male(?x), SonOf(?x, ?y), HalfSiblingOf(?y, ?z) -> NephewOf(?x, ?z)
Rule: MotherOf(?z, ?a), DaughterOf(?x, ?y), BrotherOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: MotherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: زوج العمة ل(?x, ?y) -> UncleOf(?x, ?y)
Rule: Female(?x), MotherOf(?y, ?z), HalfSisterOf(?x, ?y) -> AuntOf(?x, ?z)
Rule: Female(?x), MotherOf(?y, ?z), HalfSiblingOf(?x, ?y) -> خالة ل(?x, ?z)
Rule: Male(?a), DaughterOf(?y, ?z), SonOf(?z, ?a), BrotherOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: Female(?x), Male(?y), DaughterOf(?x, ?y), HalfSiblingOf(?y, ?z) -> ابنة الاخ ل(?x, ?z)
Rule: Female(?z), SonOf(?y, ?z), GrandSonOf(?x, ?y) -> GreatGrandMotherOf(?z, ?x)
Rule: Female(?x), Male(?y), FatherOf(?z, ?a), PartnerOf(?x, ?y), SiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: Female(?z), GrandSonOf(?y, ?z), SiblingOf(?x, ?y) -> GrandMotherOf(?z, ?x)
Rule: GivenSonOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), BrotherOf(?y, ?z) -> CousineDe(?x, ?a)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), SiblingOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: Male(?x), FatherOf(?y, ?z), HalfSiblingOf(?x, ?y) -> عم ل(?x, ?z)
Rule: PacséeÀ(?x, ?y), عم ل(?y, ?z) -> زوجة العم ل(?x, ?z)
Rule: SonOf(?x, ?y), AuntOf(?y, ?z) -> CousinDe(?x, ?z)
Rule: FatherOf(?z, ?a), PolyandrousWifeOf(?x, ?y), BrotherOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: Female(?x), PartnerOf(?x, ?y) -> مرتبطة ب(?x, ?y)
Rule: Female(?z), GrandSonOf(?y, ?z), BrotherOf(?x, ?y) -> GrandMotherOf(?z, ?x)
Rule: MotherOf(?y, ?z), SisterOf(?x, ?y) -> خالة ل(?x, ?z)
Rule: FatherOf(?z, ?a), StraightHusbandOf(?x, ?y), SisterOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: ابنة خال ل(?x, ?y) -> CousinOf(?x, ?y)
Rule: Female(?y), MotherOf(?z, ?a), PolygynousHusbandOf(?x, ?y), SiblingOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: Male(?x), SonOf(?x, ?y), BrotherOf(?y, ?z) -> NephewOf(?x, ?z)
Rule: AdoptedDaughterOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: NaturalDaughterOf(?x, ?y) -> DaughterOf(?x, ?y)
Rule: Female(?x), Male(?y), MotherOf(?z, ?a), CommonLawWifeOf(?x, ?y), HalfSiblingOf(?y, ?z) -> زوجة الخال ل(?z, ?a)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), HalfBrotherOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), HalfBrotherOf(?y, ?z) -> ابن عم ل(?x, ?a)
Rule: DaughterOf(?x, ?y), خال ل(?y, ?z) -> CousineDe(?x, ?z)
Rule: BiologicalDaughterOf(?x, ?y) -> DaughterOf(?x, ?y)
Rule: MotherOf(?y, ?z), HalfSisterOf(?x, ?y) -> خالة ل(?x, ?z)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), HalfSiblingOf(?y, ?z) -> CousineDe(?x, ?a)
Rule: Male(?x), DaughterOf(?y, ?z), SonOf(?x, ?y) -> GrandSonOf(?x, ?z)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), HalfSiblingOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: EggDonorOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: StraightHusbandOf(?x, ?y), عمة ل(?y, ?z) -> زوج العمة ل(?x, ?z)
Rule: Female(?x), PartnerOf(?x, ?y), خال ل(?y, ?z) -> زوجة الخال ل(?x, ?z)
Rule: Male(?z), FatherOf(?x, ?y), FatherOf(?y, ?z) -> GrandSonOf(?z, ?x)
Rule: Female(?z), FatherOf(?x, ?y), SiblingOf(?y, ?z) -> DaughterOf(?z, ?x)
Rule: خالة ل(?x, ?y) -> AuntOf(?x, ?y)
Rule: SonOf(?x, ?y), عم ل(?y, ?z) -> CousinOf(?x, ?z)
Rule: MotherOf(?z, ?a), SonOf(?x, ?y), BrotherOf(?y, ?z) -> CousinDe(?x, ?a)
Rule: SonOf(?x, ?y), عمة ل(?y, ?z) -> CousinOf(?x, ?z)
Rule: FatherOf(?y, ?z), ابنة الاخ ل(?x, ?y) -> ابنة عم ل(?x, ?z)
Rule: Male(?z), MotherOf(?x, ?y), MotherOf(?y, ?z) -> GrandSonOf(?z, ?x)
Rule: ابن عم ل(?x, ?y) -> CousinDe(?x, ?y)
Rule: FatherOf(?z, ?a), PacséÀ(?x, ?y), HalfSisterOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: MotherOf(?x, ?y), SiblingOf(?y, ?z) -> MotherOf(?x, ?z)
Rule: Male(?x), PartnerOf(?x, ?y), خالة ل(?y, ?z) -> زوج الخالة ل (?x, ?z)
Rule: MotherOf(?z, ?a), StraightHusbandOf(?x, ?y), HalfSisterOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: Female(?x), MotherOf(?z, ?a), مرتبطة ب(?x, ?y), BrotherOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: MotherOf(?z, ?a), PacséeÀ(?x, ?y), HalfBrotherOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), HalfSisterOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: SurrogateOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: Female(?a), SonOf(?y, ?z), SonOf(?z, ?a), SisterOf(?x, ?y) -> GrandMotherOf(?a, ?x)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), HalfSisterOf(?y, ?z) -> إبنة عمة ل(?x, ?a)
Rule: SonOf(?x, ?y), عمة ل(?y, ?z) -> CousinDe(?x, ?z)
Rule: Male(?x), SonOf(?x, ?y), HalfSisterOf(?y, ?z) -> NephewOf(?x, ?z)
Rule: MotherOf(?z, ?a), PolygynousHusbandOf(?x, ?y), SisterOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: Female(?x), MotherOf(?y, ?a), MotherOf(?y, ?x), FatherOf(?z, ?a), FatherOf(?z, ?x) -> SisterOf(?x, ?a)
Rule: Female(?x), MotherOf(?z, ?a), StraightWifeOf(?x, ?y), BrotherOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: Female(?x), MotherOf(?b, ?a), MotherOf(?z, ?x), FatherOf(?y, ?a), FatherOf(?y, ?x) -> HalfSisterOf(?x, ?a)
Rule: Female(?a), SonOf(?y, ?z), SonOf(?z, ?a), BrotherOf(?x, ?y) -> GrandMotherOf(?a, ?x)
Rule: Female(?x), SiblingOf(?x, ?y) -> SisterOf(?x, ?y)
Rule: MotherOf(?z, ?a), SonOf(?x, ?y), SisterOf(?y, ?z) -> CousinDe(?x, ?a)
Rule: Male(?a), DaughterOf(?y, ?z), SonOf(?x, ?y), SonOf(?z, ?a) -> GreatGrandFatherOf(?a, ?x)
Rule: Female(?y), FatherOf(?z, ?a), PacséÀ(?x, ?y), HalfSiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)
Rule: FatherOf(?y, ?z), HalfBrotherOf(?x, ?y) -> UncleOf(?x, ?z)
Rule: Female(?a), DaughterOf(?y, ?z), DaughterOf(?z, ?a), SonOf(?x, ?y) -> GreatGrandMotherOf(?a, ?x)
Rule: CommonLawHusbandOf(?x, ?y), خالة ل(?y, ?z) -> زوج الخالة ل (?x, ?z)
Rule: DonorFatherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: FatherOf(?z, ?a), DaughterOf(?x, ?y), SisterOf(?y, ?z) -> CousineDe(?x, ?a)
Rule: SonOf(?x, ?y), عم ل(?y, ?z) -> CousinDe(?x, ?z)
Rule: MotherOf(?y, ?z), ابنة الاخ ل(?x, ?y) -> ابنة خال ل(?x, ?z)
Rule: PacséÀ(?x, ?y), عمة ل(?y, ?z) -> زوج العمة ل(?x, ?z)
Rule: Female(?a), DaughterOf(?z, ?a), SonOf(?y, ?z), SisterOf(?x, ?y) -> GrandMotherOf(?a, ?x)
Rule: Male(?x), CommonLawHusbandOf(?x, ?y), DaughterOf(?y, ?z) -> SonInLawOf(?x, ?z)
Rule: ExHusbandOf(?x, ?y) -> SeparatedFrom(?x, ?y)
Rule: WidowerOf(?x, ?y) -> SéparéDe(?x, ?y)
Rule: Male(?x), مرتبط ب (?x, ?y), SonOf(?y, ?z) -> SonInLawOf(?x, ?z)
Rule: Male(?y), MotherOf(?z, ?a), PacséeÀ(?x, ?y), SiblingOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: زوج الخالة ل (?x, ?y) -> UncleOf(?x, ?y)
Rule: FatherOf(?z, ?a), مرتبطة ب(?x, ?y), HalfBrotherOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: MotherOf(?z, ?a), CommonLawHusbandOf(?x, ?y), SisterOf(?y, ?z) -> زوج الخالة ل (?x, ?a)
Rule: GayHusbandOf(?x, ?y) -> مرتبط ب (?x, ?y)
Rule: Female(?y), Male(?x), SonOf(?x, ?y), HalfSiblingOf(?y, ?z) -> إبن الأ خت ل(?x, ?z)
Rule: Male(?y), GrandFatherOf(?x, ?y), GrandFatherOf(?x, ?z) -> CousinDe(?y, ?z)
Rule: Female(?z), FatherOf(?x, ?y), SisterOf(?y, ?z) -> DaughterOf(?z, ?x)
Rule: Female(?x), CommonLawWifeOf(?x, ?y), SonOf(?y, ?z) -> DaughterInLawOf(?x, ?z)
Rule: Female(?x), FatherOf(?z, ?a), PartnerOf(?x, ?y), HalfBrotherOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: GrandMotherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: MotherOf(?z, ?a), DaughterOf(?x, ?y), BrotherOf(?y, ?z) -> CousineDe(?x, ?a)
Rule: Male(?y), FatherOf(?z, ?a), CommonLawWifeOf(?x, ?y), SiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: Female(?x), DaughterOf(?x, ?y), HalfSiblingOf(?y, ?z) -> NieceOf(?x, ?z)
Rule: MotherOf(?y, ?z), MotherOf(?z, ?a), FatherOf(?x, ?y) -> GreatGrandFatherOf(?x, ?a)
Rule: Male(?a), DaughterOf(?y, ?z), SonOf(?z, ?a), SisterOf(?x, ?y) -> GrandFatherOf(?a, ?x)
Rule: Female(?x), MotherOf(?z, ?a), CommonLawWifeOf(?x, ?y), HalfBrotherOf(?y, ?z) -> زوجة الخال ل(?x, ?a)
Rule: SonOf(?x, ?y), خال ل(?y, ?z) -> CousinDe(?x, ?z)
Rule: SéparéeDe(?x, ?y) -> SeparatedFrom(?x, ?y)
Rule: ابن خال ل (?x, ?y) -> CousinDe(?x, ?y)
Rule: مرتبطة ب(?x, ?y) -> PartnerOf(?x, ?y)
Rule: Female(?x), DaughterOf(?x, ?y), HalfSisterOf(?y, ?z) -> ابنة الاخت ل(?x, ?z)
Rule: StraightWifeOf(?x, ?y) -> PartnerOf(?x, ?y)
Rule: BiologicalFatherOf(?x, ?y) -> AncestorOf(?x, ?y)
Rule: GrandDaughterOf(?x, ?y) -> DescendantOf(?x, ?y)
Rule: MotherOf(?y, ?z), إبن الأخ ل(?x, ?y) -> CousinDe(?x, ?z)
Rule: MotherOf(?y, ?z), إبن الأ خت ل(?x, ?y) -> CousinDe(?x, ?z)
Rule: Male(?a), DaughterOf(?x, ?y), SonOf(?y, ?z), SonOf(?z, ?a) -> GreatGrandFatherOf(?a, ?x)
Rule: DaughterOf(?x, ?y), AuntOf(?y, ?z) -> CousinOf(?x, ?z)
Rule: Male(?a), DaughterOf(?x, ?y), DaughterOf(?y, ?z), SonOf(?z, ?a) -> GreatGrandFatherOf(?a, ?x)
Rule: FatherOf(?y, ?z), إبن الأخ ل(?x, ?y) -> ابن عم ل(?x, ?z)
Rule: MotherOf(?z, ?a), DaughterOf(?x, ?y), SiblingOf(?y, ?z) -> CousinOf(?x, ?a)
Rule: DaughterOf(?x, ?y), UncleOf(?y, ?z) -> CousinOf(?x, ?z)
Rule: Male(?x), PartnerOf(?x, ?y), عمة ل(?y, ?z) -> زوج العمة ل(?x, ?z)
Rule: CousineDe(?x, ?y) -> CousinOf(?x, ?y)
Rule: Male(?x), SonOf(?x, ?y), HalfBrotherOf(?y, ?z) -> إبن الأخ ل(?x, ?z)
Rule: SonOf(?x, ?y), UncleOf(?y, ?z) -> CousinOf(?x, ?z)
Rule: Male(?y), FatherOf(?z, ?a), PacséeÀ(?x, ?y), HalfSiblingOf(?y, ?z) -> زوجة العم ل(?x, ?a)
Rule: Female(?x), FatherOf(?y, ?z), HalfSisterOf(?x, ?y) -> AuntOf(?x, ?z)
Rule: Male(?x), SonOf(?x, ?y), BrotherOf(?y, ?z) -> إبن الأخ ل(?x, ?z)
Rule: DaughterOf(?x, ?y), خالة ل(?y, ?z) -> CousinOf(?x, ?z)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), HalfBrotherOf(?y, ?z) -> CousinDe(?x, ?a)
Rule: FatherOf(?z, ?a), SonOf(?x, ?y), HalfSisterOf(?y, ?z) -> إبن عمة ل(?x, ?a)
Rule: LegalMotherOf(?x, ?y) -> MotherOf(?x, ?y)
Rule: PolygynousHusbandOf(?x, ?y), عمة ل(?y, ?z) -> زوج العمة ل(?x, ?z)
Rule: GrandMotherOf(?y, ?z), FatherOf(?x, ?y) -> GreatGrandFatherOf(?x, ?z)
Rule: Female(?y), FatherOf(?z, ?a), PacséÀ(?x, ?y), SiblingOf(?y, ?z) -> زوج العمة ل(?x, ?a)

In [4]:
# example 
from owlready2 import get_ontology, Thing, Property, sync_reasoner_pellet

# Load the ontology
onto = get_ontology("https://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.owl").load()

# Helper function to get or create an individual
def get_or_create_individual(onto, name):
    for cls in onto.classes():
        if cls.name == "Person":
            Person = cls
            break
    individual = onto.search_one(iri=f"*#{name}")
    
    if not individual:
        individual = Person(name)
    return individual

def get_english_label(labels):
    
    for label in labels:
        if label.lang == 'en':
            return str(label)
    return None
def get_property_by_english_label(onto, label_name):
    for prop in onto.object_properties():
        
        label = get_english_label(prop.label)
        if label == label_name:
            return prop
    return None

# Add data to the ontology
def add_relation(onto, person1_name, person2_name, relation_name):
    person1 = get_or_create_individual(onto, person1_name)
    person2 = get_or_create_individual(onto, person2_name)
    relation = get_property_by_english_label(onto, relation_name)

    if relation:
        relation[person1].append(person2)
        print(f"Added relation: {person1_name} -- {relation_name} --> {person2_name}")
    else:
        print(f"Relation '{relation_name}' not found in the ontology")


def add_relation(onto, person1_name, person2_name, relation_name):
    person1 = get_or_create_individual(onto, person1_name)
    person2 = get_or_create_individual(onto, person2_name)
    relation = get_property_by_english_label(onto, relation_name)

    if relation:
        relation[person1].append(person2)
        print(f"Added relation: {person1_name} -- {relation_name} --> {person2_name}")
    else:
        print(f"Relation '{relation_name}' not found in the ontology")

In [2]:

ontology_path = "https://cedric.cnam.fr/~hamdif/ontologies/files/PersonLink.owl"
onto = get_ontology(ontology_path).load(reload=True)
onto.save(file="data/exp_ontology.owl")
# def check_consistency_and_explain(ontology):
#     try:
#         with onto:
#             sync_reasoner(infer_property_values=True)
#         print("The ontology is consistent.")
#     except OwlReadyInconsistentOntologyError:
#         print("The ontology is inconsistent.")
#         inconsistencies = ontology.world.inconsistent_individuals()
#         print("Inconsistent individuals:", inconsistencies)
#         explanation = ontology.world.explain_inconsistency()
#         print("Explanation for inconsistency:")
#         for axiom in explanation:
#             print(axiom)
#     except OwlReadyJavaError as e:
#         print(f"Java error during reasoning: {e}")
#         print("Java error output:")
#         print(e.args[0])
#     except Exception as e:
#         print(f"An unexpected error occurred: {e}")

# # Check for inconsistencies and explain them
# check_consistency_and_explain(onto)

In [8]:
from owlready2 import  *
ontology_path = "../code/full"
onto = get_ontology(ontology_path).load(reload=True)

sync_reasoner(infer_property_values=True)
# Function to check consistency and explain
# def check_consistency_and_explain(ontology):
#     try:
#         with ontology:
           
#         print("The ontology is consistent.")
#     except OwlReadyInconsistentOntologyError:
#         print("The ontology is inconsistent.")
        
#         # Check for inconsistent individuals and their explanations
#         inconsistent_individuals = list(default_world.inconsistent_classes())
#         print("Inconsistent individuals found:")
#         for ind in inconsistent_individuals:
#             print(f"Inconsistent individual: {ind.name}")
#             print
#             for reason in ind.is_a:
#                 print(f"  Reason: {reason}")
#     except OwlReadyJavaError as e:
#         print(f"Java error during reasoning: {e}")
#         print("Java error output:")
#         print(e.args[0])
#     except Exception as e:
#         print(f"An unexpected error occurred: {e}")

# # Check consistency and explain
# check_consistency_and_explain(onto)

* Owlready2 * Running HermiT...
    java -Xmx2000M -cp c:\Python312\Lib\site-packages\owlready2\hermit;c:\Python312\Lib\site-packages\owlready2\hermit\HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:///C:/Users/JA194F~1.BOR/AppData/Local/Temp/tmpsv6824y5 -Y

OwlReadyInconsistentOntologyError:

In [10]:
# Function to get the English label of an entity
def get_label(entity):
    
    if hasattr(entity, 'label') and entity.label:
        for i in entity.label:
            if i.lang == 'en':
                return i
        
    else:
        return entity.name

# Function to print all relations in the ontology with English names
def print_all_relations(ontology):
    print("Listing all relations in the ontology:\n")
    
    # Print object properties and their relations
    print("Object Properties:")
    for obj_property in ontology.object_properties():
        property_label = get_label(obj_property)
        print(f"Property: {property_label}")
        for value in obj_property.get_relations():
            subject_label = get_label(value[0])
            object_label = get_label(value[1])
            print(f"  {subject_label} -- {property_label} --> {object_label}")



# Print all relations
print_all_relations(onto)

Listing all relations in the ontology:

Object Properties:
Property: AncestorOf
Property: ancestorOf
Property: GreatGrandParentOf
Property: GreatGrandMotherOf
Property: GreatGrandFatherOf
Property: GrandParentOf
Property: grandparentOf
Property: GrandMotherOf
  Mary -- GrandMotherOf --> Ola
Property: GrandFatherOf
Property: ParentOf
Property: parentOf
Property: MotherOf
  Mary -- MotherOf --> Alice
  Alice -- MotherOf --> Ola
Property: LegalMotherOf
Property: BiologicalMotherOf
Property: EggDonorOf
Property: NaturalMotherOf
Property: SurrogateOf
Property: FatherOf
Property: LegalFatherOf
Property: BiologicalFatherOf
Property: DonorFatherOf
Property: NaturalFatherOf
Property: NieceOf
Property: None
Property: None
Property: NephewOf
Property: None
Property: None
Property: SeparatedFrom
Property: None
Property: ExCommonLawWifeOf
Property: ExWifeOf
Property: ExGayWifeOf
Property: ExStraightWifeOf
Property: ExPolyandrousWifeOf
Property: WidowOf
Property: None
Property: None
Property: ExCommonLawHusbandOf
Property: ExHusbandOf
Property: ExGayHusbandOf
Property: ExStraightHusbandOf
Property: ExPolygynousHusbandOf
Property: WidowerOf
Property: None
Property: PartnerOf
Property: None
Property: CommonLawWifeOf
Property: WifeOf
Property: GayWifeOf
Property: StraightWifeOf
Property: PolyandrousWifeOf
Property: None
Property: None
Property: CommonLawHusbandOf
Property: HusbandOf
  John -- HusbandOf --> Mary
  Bart -- HusbandOf --> Alice
Property: GayHusbandOf
Property: StraightHusbandOf
Property: PolygynousHusbandOf
Property: None
Property: CousinOf
  Ola -- CousinOf --> Ola
Property: None
Property: None
Property: None
Property: None
Property: None
Property: None
Property: None
Property: None
Property: None
Property: None
Property: DescendantOf
Property: descendantOf
Property: ChildOf
Property: childOf
Property: DaughterOf
Property: AdoptedDaughterOf
Property: BiologicalDaughterOf
Property: GivenGirlOf
Property: NaturalDaughterOf
Property: SurrogateDaughterOf
Property: SonOf
Property: AdoptedSonOf
Property: BiologicalSonOf
Property: GivenSonOf
Property: NaturalSonOf
Property: SurrogateSonOf
Property: GrandChildOf
Property: grandchildOf
Property: GrandDaughterOf
Property: GrandSonOf
Property: HalfSiblingOf
Property: SiblingOf
Property: siblingOf
Property: HalfSisterOf
Property: HalfBrotherOf
Property: SisterOf
Property: BrotherOf
Property: DaughterInLawOf
Property: SonInLawOf
Property: AuntOf
Property: None
Property: None
Property: None
Property: None
Property: UncleOf
Property: None
Property: None
Property: None
Property: None